/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Steganografi;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.Arrays;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author Acer
 */
public class View extends javax.swing.JFrame {
   
 char [] e_pass = null;
    /**
     * Creates new form View
     */
   
    public View() {
        initComponents();
        this.setLocationRelativeTo(null);
        objPass.getBtnSend().addActionListener(new Actionlistener(){
            
            public void actionPerformed(ActionEvent e){
                e_pass = objPass.getPass().getPassword();
                objPass.bersihPass();
                setFocusable(true);
            }
       
        });
 
  
    }
//Deklarasi dan inisialisasi objek password dialog
   private final PasswordDialog objPass = new PasswordDialog(this,rootPaneCheckingEnabled);
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabMenuUtama = new javax.swing.JTabbedPane();
        pnlTabEmbed = new javax.swing.JPanel();
        btnAddFile = new javax.swing.JButton();
        btnCoverImage = new javax.swing.JButton();
        btnEncode = new javax.swing.JButton();
        lblFileMessage = new javax.swing.JLabel();
        lblFileName = new javax.swing.JLabel();
        txtDirektori = new javax.swing.JTextField();
        pnlCoverImage = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lblCoverImage = new javax.swing.JLabel();
        pnlStegoImage = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lblStegoImage = new javax.swing.JLabel();
        txtStegoImage = new javax.swing.JTextField();
        StegoImage = new javax.swing.JLabel();
        CoverImage = new javax.swing.JLabel();
        btnPassword = new javax.swing.JToggleButton();
        pnlTabExtract = new javax.swing.JPanel();
        txtDirektori2 = new javax.swing.JTextField();
        btnAddStego = new javax.swing.JButton();
        pnlCoverImage_2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lblStegoImage2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        btnExtrak = new javax.swing.JButton();
        txtNamaFile = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAddFile.setText("Add File");
        btnAddFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFileActionPerformed(evt);
            }
        });

        btnCoverImage.setText("Cover Image");
        btnCoverImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoverImageActionPerformed(evt);
            }
        });

        btnEncode.setText("Encode");
        btnEncode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncodeActionPerformed(evt);
            }
        });

        lblFileMessage.setText("Message Fie");

        lblFileName.setText("File Nama ");

        jScrollPane2.setViewportView(lblCoverImage);

        javax.swing.GroupLayout pnlCoverImageLayout = new javax.swing.GroupLayout(pnlCoverImage);
        pnlCoverImage.setLayout(pnlCoverImageLayout);
        pnlCoverImageLayout.setHorizontalGroup(
            pnlCoverImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
        );
        pnlCoverImageLayout.setVerticalGroup(
            pnlCoverImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jScrollPane3.setViewportView(lblStegoImage);

        javax.swing.GroupLayout pnlStegoImageLayout = new javax.swing.GroupLayout(pnlStegoImage);
        pnlStegoImage.setLayout(pnlStegoImageLayout);
        pnlStegoImageLayout.setHorizontalGroup(
            pnlStegoImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
        );
        pnlStegoImageLayout.setVerticalGroup(
            pnlStegoImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
        );

        StegoImage.setText("Stego Image");

        CoverImage.setText("Cover Image");

        btnPassword.setText("Password");
        btnPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTabEmbedLayout = new javax.swing.GroupLayout(pnlTabEmbed);
        pnlTabEmbed.setLayout(pnlTabEmbedLayout);
        pnlTabEmbedLayout.setHorizontalGroup(
            pnlTabEmbedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabEmbedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTabEmbedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTabEmbedLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAddFile, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCoverImage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEncode))
                    .addGroup(pnlTabEmbedLayout.createSequentialGroup()
                        .addGroup(pnlTabEmbedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CoverImage, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlCoverImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlTabEmbedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StegoImage, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlStegoImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 33, Short.MAX_VALUE))
                    .addGroup(pnlTabEmbedLayout.createSequentialGroup()
                        .addGroup(pnlTabEmbedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblFileName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFileMessage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlTabEmbedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDirektori)
                            .addGroup(pnlTabEmbedLayout.createSequentialGroup()
                                .addComponent(txtStegoImage, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        pnlTabEmbedLayout.setVerticalGroup(
            pnlTabEmbedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabEmbedLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlTabEmbedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddFile)
                    .addComponent(btnCoverImage)
                    .addComponent(btnEncode)
                    .addComponent(btnPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTabEmbedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFileMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDirektori, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTabEmbedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStegoImage, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlTabEmbedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StegoImage)
                    .addComponent(CoverImage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlTabEmbedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlStegoImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlCoverImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tabMenuUtama.addTab("Encode Message", pnlTabEmbed);

        btnAddStego.setText("Add Stego Image");
        btnAddStego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStegoActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lblStegoImage2);

        jLabel1.setText("Stego Image");

        javax.swing.GroupLayout pnlCoverImage_2Layout = new javax.swing.GroupLayout(pnlCoverImage_2);
        pnlCoverImage_2.setLayout(pnlCoverImage_2Layout);
        pnlCoverImage_2Layout.setHorizontalGroup(
            pnlCoverImage_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCoverImage_2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCoverImage_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlCoverImage_2Layout.setVerticalGroup(
            pnlCoverImage_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCoverImage_2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel3.setText("Password ");

        jLabel4.setText("Nama File Hasil Ekstrak");

        btnExtrak.setText("Ekstrak");
        btnExtrak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExtrakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTabExtractLayout = new javax.swing.GroupLayout(pnlTabExtract);
        pnlTabExtract.setLayout(pnlTabExtractLayout);
        pnlTabExtractLayout.setHorizontalGroup(
            pnlTabExtractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabExtractLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTabExtractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTabExtractLayout.createSequentialGroup()
                        .addComponent(pnlCoverImage_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnlTabExtractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNamaFile)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTabExtractLayout.createSequentialGroup()
                                .addGap(0, 105, Short.MAX_VALUE)
                                .addComponent(btnExtrak, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtPass)
                            .addGroup(pnlTabExtractLayout.createSequentialGroup()
                                .addGroup(pnlTabExtractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(pnlTabExtractLayout.createSequentialGroup()
                        .addComponent(txtDirektori2, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddStego)))
                .addContainerGap())
        );
        pnlTabExtractLayout.setVerticalGroup(
            pnlTabExtractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabExtractLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTabExtractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddStego)
                    .addComponent(txtDirektori2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlTabExtractLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTabExtractLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNamaFile, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExtrak)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTabExtractLayout.createSequentialGroup()
                        .addComponent(pnlCoverImage_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        tabMenuUtama.addTab("Decode Message", pnlTabExtract);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabMenuUtama)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabMenuUtama)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


private File pilihFile(){
            JFileChooser pilih = new JFileChooser();
            int dapat = pilih.showDialog(null, null);
            if(dapat == JFileChooser.APPROVE_OPTION){
                File direktori = pilih.getSelectedFile();
                return direktori;
            }
            return null;
        }
    private void btnCoverImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoverImageActionPerformed
        // TODO add your handling code here:
        
        try{
        File file = pilihFile();
        lblCoverImage.setIcon(new ImageIcon(ImageIO.read(new File(file.getPath()))));
            String coverpath = file.getPath();
                }catch (Exception e) {
                    System.out.println(e.getMessage());
                    
                }
        
        
        
    }//GEN-LAST:event_btnCoverImageActionPerformed
byte [] pesan = null;
    private void btnAddFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFileActionPerformed
        // TODO add your handling code here:
         String ext = "";
         String extension ="";
         try{
             File file = pilihFile();
             byte[] bytefile = getBytesFromFile(file);
             System.out.println(""+ Arrays.toString(bytefile));
             try (FileOutputStream out = new FileOutputStream("dummy")) {
                 out.write(bytefile);
                 
                 ext = file.getName();
                 int i = ext.lastIndexOf('.');
                 if (i>0 && i <1-ext.length()){
                     ext=ext.substring(i).toLowerCase();
                     extension = "@ext="+ext;
                     out.write(extension.getBytes());
                 }
             }
             
             File temp_file = new File ("dummy");
             pesan = getBytesFromFile(temp_file);
             txtDirektori.setText(file.getPath());
             temp_file.delete();
         } catch (Exception e){
             System.out.println(""+e.getMessage());
             
             }
         
    }//GEN-LAST:event_btnAddFileActionPerformed

    private void btnEncodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncodeActionPerformed
        // TODO add your handling code here:
        
        Controller objController = new Controller();
        pesan = objController.encryp(pesan, e_pass);
        System.out.println("Pesan Sesudah Enkrip : "+ pesan);
        //Untuk menyisipkan pesannya
        try {
            String coverpath = null;
            File a = objController.embed(coverpath, txtStegoImage.getText(),pesan);
            lblStegoImage.setIcon(new ImageIcon(ImageIO.read(new File(a.getPath()))));
        }catch (Exception e){
            
        } 
    }//GEN-LAST:event_btnEncodeActionPerformed

    private void btnPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasswordActionPerformed
        // TODO add your handling code here:
        objPass.setVisible(true);
    }//GEN-LAST:event_btnPasswordActionPerformed

    private void btnAddStegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStegoActionPerformed
        // TODO add your handling code here:
            try {
    File file = pilihFile();
    txtDirektori2.setText(file.getPath());
   lblStegoImage2.setIcon(new ImageIcon(ImageIO.read(new File(file.getPath()))));
    } catch (Exception e){
                System.out.println(e.getMessage());
    }

    }//GEN-LAST:event_btnAddStegoActionPerformed

    private void btnExtrakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExtrakActionPerformed
        // TODO add your handling code here:
            try {
                 file_name = txtNamaFile.getText();
        byte[] message = new Controller().extract(txtDirektori2.getText());
        message = new Controller().decrypt(message, txtPass.getPassword());
    } catch (Exception e){
    }

            try {
 		file_name = txtNamaFile.getText();
                byte[] message = new Controller().extract(txtDirektori2.getText());
 		message = new Controller().decrypt(message, txtPass.getPassword());

 		String param = null;
 		String ext = new String(message);

 		int i = ext.lastIndexOf("@ext=");
 		if (i > 0 && i < ext.length() - 1 ) {
                        ext = ext.substring(i+5).toLowerCase();
 			file_name = file_name + ext;
 			param = ext;

 		}
 		String dir = " Extracted message";
 		try {
 			new File(dir).mkdir();

 		} catch (Exception ex) {

 		}
 		byte a;
 		x_file = new FileOutputStream(dir + "/" + file_name);
 		for (int j = 0; j < (message.length - (5 + param.length())); j++){
 			a = message[j];
 			x_file.write(a);

 		}
 		x_file.close();

 	}catch (Exception e){
 		
 	}
    }//GEN-LAST:event_btnExtrakActionPerformed
public byte[] getBytesFromFile(File file) throws IOException{
    byte[] bytes;
        try (InputStream is = new FileInputStream(file)) {
            long length = file.length();
            bytes = new byte[(int)length];
            int offset = 0;
            int numRead = 0;
            while (offset <bytes.length && (numRead = is.read(bytes,offset, bytes.length-offset)) >=0){
                offset += numRead;
                
            }       if (offset < bytes.length){
                throw new IOException("not completely"+ file.getName());
        
    }   }
        return bytes;
     
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } 

catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
char[] e_pass = null;
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }
    
String file_name = null;
FileOutputStream x_file = null;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CoverImage;
    private javax.swing.JLabel StegoImage;
    private javax.swing.JButton btnAddFile;
    private javax.swing.JButton btnAddStego;
    private javax.swing.JButton btnCoverImage;
    private javax.swing.JButton btnEncode;
    private javax.swing.JButton btnExtrak;
    private javax.swing.JToggleButton btnPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCoverImage;
    private javax.swing.JLabel lblFileMessage;
    private javax.swing.JLabel lblFileName;
    private javax.swing.JLabel lblStegoImage;
    private javax.swing.JLabel lblStegoImage2;
    private javax.swing.JPanel pnlCoverImage;
    private javax.swing.JPanel pnlCoverImage_2;
    private javax.swing.JPanel pnlStegoImage;
    private javax.swing.JPanel pnlTabEmbed;
    private javax.swing.JPanel pnlTabExtract;
    private javax.swing.JTabbedPane tabMenuUtama;
    private javax.swing.JTextField txtDirektori;
    private javax.swing.JTextField txtDirektori2;
    private javax.swing.JTextField txtNamaFile;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtStegoImage;
    // End of variables declaration//GEN-END:variables

    private static abstract class Actionlistener implements ActionListener {

        public Actionlistener() {
        }
    }

  

}
